export const PINNED_TOKEN_TRACKER_VERSION = "0.80.0" as const;

export const DEFAULT_TOKEN_TRACKER_STARTUP_TIMEOUT_MS = 45_000;
export const DEFAULT_TOKEN_TRACKER_REFRESH_TIMEOUT_MS = 45_000;
export const DEFAULT_TOKEN_TRACKER_SHUTDOWN_TIMEOUT_MS = 5_000;
export const DEFAULT_TOKEN_TRACKER_REFRESH_INTERVAL_MS = 60_000;

export const MAX_TOKEN_TRACKER_STARTUP_TIMEOUT_MS = 120_000;
export const MAX_TOKEN_TRACKER_REFRESH_TIMEOUT_MS = 120_000;
export const MAX_TOKEN_TRACKER_SHUTDOWN_TIMEOUT_MS = 15_000;
export const MIN_TOKEN_TRACKER_REFRESH_INTERVAL_MS = 10_000;
